name: be_fit_real
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  # VersiÃ³n compatible que no da problemas
  google_fonts: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # ðŸŸ¢ IMPORTANTE: La indentaciÃ³n exacta es clave aquÃ­
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_con_margen.png" # <--- Tu ruta al logo
  min_sdk_android: 21 # Importante para evitar errores
  adaptive_icon_background: "#1E1E1E" # Color de fondo (Gris oscuro corporativo)
  adaptive_icon_foreground: "assets/images/logo_con_margen.png" # El logo en sÃ­